version: '3'

volumes:
  mysql_data:
    name: mysql_data
    driver: local

networks:
  mysql:
    name: mysql
    driver: bridge

services:
  backend:
    init: true
    image: docker.io/newjett0617/realworld:backend
    container_name: backend
    networks:
      - mysql
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
  mysql:
    init: true
    image: docker.io/library/mysql:5.7
    container_name: mysql
    networks:
      - mysql
    expose:
      - 3306
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=realworld
      - MYSQL_PASSWORD=realworld
      - MYSQL_DATABASE=realworld
    volumes:
      - mysql_data:/var/lib/mysql
